# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"G\n\tStockItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"m\n\rUpdateSummary\x12\x17\n\x0ftotal_processed\x18\x01 \x01(\x05\x12\x1a\n\x12successful_updates\x18\x02 \x01(\x05\x12\x16\n\x0e\x66\x61iled_updates\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2\x94\x01\n\x10InventoryControl\x12\x45\n\x0f\x42ulkUpdateStock\x12\x14.inventory.StockItem\x1a\x18.inventory.UpdateSummary\"\x00(\x01\x12\x39\n\tClearData\x12\x10.inventory.Empty\x1a\x18.inventory.UpdateSummary\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKITEM']._serialized_start=30
  _globals['_STOCKITEM']._serialized_end=101
  _globals['_UPDATESUMMARY']._serialized_start=103
  _globals['_UPDATESUMMARY']._serialized_end=212
  _globals['_EMPTY']._serialized_start=214
  _globals['_EMPTY']._serialized_end=221
  _globals['_INVENTORYCONTROL']._serialized_start=224
  _globals['_INVENTORYCONTROL']._serialized_end=372
# @@protoc_insertion_point(module_scope)
