# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x07message\"#\n\x0fPasswordRequest\x12\x10\n\x08password\x18\x01 \x01(\t\"$\n\x10PasswordResponse\x12\x10\n\x08strength\x18\x01 \x01(\t\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"#\n\x11\x45mailListResponse\x12\x0e\n\x06\x65mails\x18\x01 \x03(\t2\xd7\x01\n\x0eMessageService\x12\x44\n\rCheckPassword\x12\x18.message.PasswordRequest\x1a\x19.message.PasswordResponse\x12<\n\rTransliterate\x12\x14.message.TextRequest\x1a\x15.message.TextResponse\x12\x41\n\rExtractEmails\x12\x14.message.TextRequest\x1a\x1a.message.EmailListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSWORDREQUEST']._serialized_start=34
  _globals['_PASSWORDREQUEST']._serialized_end=69
  _globals['_PASSWORDRESPONSE']._serialized_start=71
  _globals['_PASSWORDRESPONSE']._serialized_end=107
  _globals['_TEXTREQUEST']._serialized_start=109
  _globals['_TEXTREQUEST']._serialized_end=136
  _globals['_TEXTRESPONSE']._serialized_start=138
  _globals['_TEXTRESPONSE']._serialized_end=168
  _globals['_EMAILLISTRESPONSE']._serialized_start=170
  _globals['_EMAILLISTRESPONSE']._serialized_end=205
  _globals['_MESSAGESERVICE']._serialized_start=208
  _globals['_MESSAGESERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
