# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_service_pb2 as message__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPassword = channel.unary_unary(
                '/message.MessageService/CheckPassword',
                request_serializer=message__service__pb2.PasswordRequest.SerializeToString,
                response_deserializer=message__service__pb2.PasswordResponse.FromString,
                _registered_method=True)
        self.Transliterate = channel.unary_unary(
                '/message.MessageService/Transliterate',
                request_serializer=message__service__pb2.TextRequest.SerializeToString,
                response_deserializer=message__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.ExtractEmails = channel.unary_unary(
                '/message.MessageService/ExtractEmails',
                request_serializer=message__service__pb2.TextRequest.SerializeToString,
                response_deserializer=message__service__pb2.EmailListResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transliterate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEmails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPassword,
                    request_deserializer=message__service__pb2.PasswordRequest.FromString,
                    response_serializer=message__service__pb2.PasswordResponse.SerializeToString,
            ),
            'Transliterate': grpc.unary_unary_rpc_method_handler(
                    servicer.Transliterate,
                    request_deserializer=message__service__pb2.TextRequest.FromString,
                    response_serializer=message__service__pb2.TextResponse.SerializeToString,
            ),
            'ExtractEmails': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEmails,
                    request_deserializer=message__service__pb2.TextRequest.FromString,
                    response_serializer=message__service__pb2.EmailListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/CheckPassword',
            message__service__pb2.PasswordRequest.SerializeToString,
            message__service__pb2.PasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transliterate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/Transliterate',
            message__service__pb2.TextRequest.SerializeToString,
            message__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEmails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/ExtractEmails',
            message__service__pb2.TextRequest.SerializeToString,
            message__service__pb2.EmailListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
