[req]
distinguished_name = dn
prompt = no

[dn]
CN = localhost

[server_ext]
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost, DNS:127.0.0.1, IP:127.0.0.1